### ISSUE TITLE
Why is api attribute in context Mutex?

### ISSUE THREAD

**Issue by prostomarkeloff** [u32i64/vk-bot#9]
https://github.com/u32i64/vk-bot/blob/master/src/context.rs#L18

**Comment by awaitlink** [comment]
Are you generally asking what a `Mutex` is and why it's needed here, or you specifically know that it's possible to not use it here?

**Comment by prostomarkeloff** [comment]
> Are you generally asking what a `Mutex` is and why it's needed here, or you specifically know that it's possible to not use it here?

The second. I see no reasons why using it (or maybe I look bad :)).
With a half of the first :). I really don't understand why Mutex is used here.

**Comment by awaitlink** [comment]
You're right :man_facepalming:. `Arc` isn't needed as well. Sharing a `&APIClient` between threads works.

Thanks!
